# Appendix A A sample session
<p>The following session is intended to introduce to you some features of the R environment by using them. Many features of the system will be unfamiliar and puzzling at first, but this puzzlement will soon disappear.</p>
<dl>
<dt><code class="calibre2">Start R appropriately for your platform (see Invoking R).</code></dt>
<dd><p>The R program begins, with a banner.</p>
<p>(Within R code, the prompt on the left hand side will not be shown to avoid confusion.)</p>
</dd>
<dt><code class="calibre2">help.start()</code></dt>
<dd><p>Start the HTML interface to on-line help (using a web browser available at your machine). You should briefly explore the features of this facility with the mouse.</p>
<p>Iconify the help window and move on to the next part.</p>
</dd>
<dt><code class="calibre2">x &lt;- rnorm(50)</code><br />
<code class="calibre2">y &lt;- rnorm(x)</code></dt>
<dd><p>Generate two pseudo-random normal vectors of <em>x</em>- and <em>y</em>-coordinates.</p>
</dd>
<dt><code class="calibre2">plot(x, y)</code></dt>
<dd><p>Plot the points in the plane. A graphics window will appear automatically.</p>
</dd>
<dt><code class="calibre2">ls()</code></dt>
<dd><p>See which R objects are now in the R workspace.</p>
</dd>
<dt><code class="calibre2">rm(x, y)</code></dt>
<dd><p>Remove objects no longer needed. (Clean up).</p>
</dd>
<dt><code class="calibre2">x &lt;- 1:20</code></dt>
<dd><p>Make <em>x = (1, 2, …, 20)</em>.</p>
</dd>
<dt><code class="calibre2">w &lt;- 1 + sqrt(x)/2</code></dt>
<dd><p>A ‘weight’ vector of standard deviations.</p>
</dd>
<dt><code class="calibre2">dummy &lt;- data.frame(x=x, y= x + rnorm(x)*w)</code><br />
<code class="calibre2">dummy</code></dt>
<dd><p>Make a <em>data frame</em> of two columns, <em>x</em> and <em>y</em>, and look at it.</p>
</dd>
<dt><code class="calibre2">fm &lt;- lm(y ~ x, data=dummy)</code><br />
<code class="calibre2">summary(fm)</code></dt>
<dd><p>Fit a simple linear regression and look at the analysis. With <code class="calibre2">y</code> to the left of the tilde, we are modelling <em>y</em> dependent on <em>x</em>.</p>
</dd>
<dt><code class="calibre2">fm1 &lt;- lm(y ~ x, data=dummy, weight=1/w^2)</code><br />
<code class="calibre2">summary(fm1)</code></dt>
<dd><p>Since we know the standard deviations, we can do a weighted regression.</p>
</dd>
<dt><code class="calibre2">attach(dummy)</code></dt>
<dd><p>Make the columns in the data frame visible as variables.</p>
</dd>
<dt><code class="calibre2">lrf &lt;- lowess(x, y)</code></dt>
<dd><p>Make a nonparametric local regression function.</p>
</dd>
<dt><code class="calibre2">plot(x, y)</code></dt>
<dd><p>Standard point plot.</p>
</dd>
<dt><code class="calibre2">lines(x, lrf$y)</code></dt>
<dd><p>Add in the local regression.</p>
</dd>
<dt><code class="calibre2">abline(0, 1, lty=3)</code></dt>
<dd><p>The true regression line: (intercept 0, slope 1).</p>
</dd>
<dt><code class="calibre2">abline(coef(fm))</code></dt>
<dd><p>Unweighted regression line.</p>
</dd>
<dt><code class="calibre2">abline(coef(fm1), col = &quot;red&quot;)</code></dt>
<dd><p>Weighted regression line.</p>
</dd>
<dt><code class="calibre2">detach()</code></dt>
<dd><p>Remove data frame from the search path.</p>
</dd>
<dt><code class="calibre2">plot(fitted(fm), resid(fm),</code><br />
<code class="calibre2">     xlab=&quot;Fitted values&quot;,</code><br />
<code class="calibre2">     ylab=&quot;Residuals&quot;,</code><br />
<code class="calibre2">     main=&quot;Residuals vs Fitted&quot;)</code></dt>
<dd><p>A standard regression diagnostic plot to check for heteroscedasticity. Can you see it?</p>
</dd>
<dt><code class="calibre2">qqnorm(resid(fm), main=&quot;Residuals Rankit Plot&quot;)</code></dt>
<dd><p>A normal scores plot to check for skewness, kurtosis and outliers. (Not very useful here.)</p>
</dd>
<dt><code class="calibre2">rm(fm, fm1, lrf, x, dummy)</code></dt>
<dd><p>Clean up again.</p>
</dd>
</dl>
<p>The next section will look at data from the classical experiment of Michelson to measure the speed of light. This dataset is available in the <code class="calibre2">morley</code> object, but we will read it to illustrate the <code class="calibre2">read.table</code> function.</p>
<dl>
<dt><code class="calibre2">filepath &lt;- system.file(&quot;data&quot;, &quot;morley.tab&quot; , package=&quot;datasets&quot;)</code><br />
<code class="calibre2">filepath</code></dt>
<dd><p>Get the path to the data file.</p>
</dd>
<dt><code class="calibre2">file.show(filepath)</code></dt>
<dd><p>Optional. Look at the file.</p>
</dd>
<dt><code class="calibre2">mm &lt;- read.table(filepath)</code><br />
<code class="calibre2">mm</code></dt>
<dd><p>Read in the Michelson data as a data frame, and look at it. There are five experiments (column <code class="calibre2">Expt</code>) and each has 20 runs (column <code class="calibre2">Run</code>) and <code class="calibre2">sl</code> is the recorded speed of light, suitably coded.</p>
</dd>
<dt><code class="calibre2">mm$Expt &lt;- factor(mm$Expt)</code><br />
<code class="calibre2">mm$Run &lt;- factor(mm$Run)</code></dt>
<dd><p>Change <code class="calibre2">Expt</code> and <code class="calibre2">Run</code> into factors.</p>
</dd>
<dt><code class="calibre2">attach(mm)</code></dt>
<dd><p>Make the data frame visible at position 3 (the default).</p>
</dd>
<dt><code class="calibre2">plot(Expt, Speed, main=&quot;Speed of Light Data&quot;, xlab=&quot;Experiment No.&quot;)</code></dt>
<dd><p>Compare the five experiments with simple boxplots.</p>
</dd>
<dt><code class="calibre2">fm &lt;- aov(Speed ~ Run + Expt, data=mm)</code><br />
<code class="calibre2">summary(fm)</code></dt>
<dd><p>Analyze as a randomized block, with ‘runs’ and ‘experiments’ as factors.</p>
</dd>
<dt><code class="calibre2">fm0 &lt;- update(fm, . ~ . - Run)</code><br />
<code class="calibre2">anova(fm0, fm)</code></dt>
<dd><p>Fit the sub-model omitting ‘runs’, and compare using a formal analysis of variance.</p>
</dd>
<dt><code class="calibre2">detach()</code><br />
<code class="calibre2">rm(fm, fm0)</code></dt>
<dd><p>Clean up before moving on.</p>
</dd>
</dl>
<p>We now look at some more graphical features: contour and image plots.</p>
<dl>
<dt><code class="calibre2">x &lt;- seq(-pi, pi, len=50)</code><br />
<code class="calibre2">y &lt;- x</code></dt>
<dd><p><em>x</em> is a vector of 50 equally spaced values in the interval [-pi\, pi]. <em>y</em> is the same.</p>
</dd>
<dt><code class="calibre2">f &lt;- outer(x, y, function(x, y) cos(y)/(1 + x^2))</code></dt>
<dd><p><em>f</em> is a square matrix, with rows and columns indexed by <em>x</em> and <em>y</em> respectively, of values of the function cos(y)/(1 + x^2).</p>
</dd>
<dt><code class="calibre2">oldpar &lt;- par(no.readonly = TRUE)</code><br />
<code class="calibre2">par(pty=&quot;s&quot;)</code></dt>
<dd><p>Save the plotting parameters and set the plotting region to “square”.</p>
</dd>
<dt><code class="calibre2">contour(x, y, f)</code><br />
<code class="calibre2">contour(x, y, f, nlevels=15, add=TRUE)</code></dt>
<dd><p>Make a contour map of <em>f</em>; add in more lines for more detail.</p>
</dd>
<dt><code class="calibre2">fa &lt;- (f-t(f))/2</code></dt>
<dd><p><code class="calibre2">fa</code> is the “asymmetric part” of <em>f</em>. (<code class="calibre2">t()</code> is transpose).</p>
</dd>
<dt><code class="calibre2">contour(x, y, fa, nlevels=15)</code></dt>
<dd><p>Make a contour plot, …</p>
</dd>
<dt><code class="calibre2">par(oldpar)</code></dt>
<dd><p>… and restore the old graphics parameters.</p>
</dd>
<dt><code class="calibre2">image(x, y, f)</code><br />
<code class="calibre2">image(x, y, fa)</code></dt>
<dd><p>Make some high density image plots, (of which you can get hardcopies if you wish), …</p>
</dd>
<dt><code class="calibre2">objects(); rm(x, y, f, fa)</code></dt>
<dd><p>… and clean up before moving on.</p>
</dd>
</dl>
<p>R can do complex arithmetic, also.</p>
<dl>
<dt><code class="calibre2">th &lt;- seq(-pi, pi, len=100)</code><br />
<code class="calibre2">z &lt;- exp(1i*th)</code></dt>
<dd><p><code class="calibre2">1i</code> is used for the complex number <em>i</em>.</p>
</dd>
<dt><code class="calibre2">par(pty=&quot;s&quot;)</code><br />
<code class="calibre2">plot(z, type=&quot;l&quot;)</code></dt>
<dd><p>Plotting complex arguments means plot imaginary versus real parts. This should be a circle.</p>
</dd>
<dt><code class="calibre2">w &lt;- rnorm(100) + rnorm(100)*1i</code></dt>
<dd><p>Suppose we want to sample points within the unit circle. One method would be to take complex numbers with standard normal real and imaginary parts …</p>
</dd>
<dt><code class="calibre2">w &lt;- ifelse(Mod(w) &gt; 1, 1/w, w)</code></dt>
<dd><p>… and to map any outside the circle onto their reciprocal.</p>
</dd>
<dt><code class="calibre2">plot(w, xlim=c(-1,1), ylim=c(-1,1), pch=&quot;+&quot;,xlab=&quot;x&quot;, ylab=&quot;y&quot;)</code><br />
<code class="calibre2">lines(z)</code></dt>
<dd><p>All points are inside the unit circle, but the distribution is not uniform.</p>
</dd>
<dt><code class="calibre2">w &lt;- sqrt(runif(100))*exp(2*pi*runif(100)*1i)</code><br />
<code class="calibre2">plot(w, xlim=c(-1,1), ylim=c(-1,1), pch=&quot;+&quot;, xlab=&quot;x&quot;, ylab=&quot;y&quot;)</code><br />
<code class="calibre2">lines(z)</code></dt>
<dd><p>The second method uses the uniform distribution. The points should now look more evenly spaced over the disc.</p>
</dd>
<dt><code class="calibre2">rm(th, w, z)</code></dt>
<dd><p>Clean up again.</p>
</dd>
<dt><code class="calibre2">q()</code></dt>
<dd><p>Quit the R program. You will be asked if you want to save the R workspace, and for an exploratory session like this, you probably do not want to save it.</p>
</dd>
</dl>
<hr />
<p><a href="" id="Invoking-R"></a> <a href="" id="Invoking-R-1"></a></p>
