# Appendix C The command-line editor
<p><a href="" id="Preliminaries"></a></p>
<h3 id="c.1-preliminaries" class="section">C.1 Preliminaries</h3>
<p>When the GNU <strong>readline</strong> library is available at the time R is configured for compilation under UNIX, an inbuilt command line editor allowing recall, editing and re-submission of prior commands is used. Note that other versions of <strong>readline</strong> exist and may be used by the inbuilt command line editor: this used to happen on macOS.</p>
<p>It can be disabled (useful for usage with ESS <a href="023-R-intro.html#FOOT27" id="DOCF27"><sup>27</sup></a>) using the startup option --no-readline.</p>
<p>Windows versions of R have somewhat simpler command-line editing: see ‘Console’ under the ‘Help’ menu of the GUI, and the file README.Rterm for command-line editing under <code class="calibre2">Rterm.exe</code>.</p>
<p>When using R with GNU<a href="023-R-intro.html#FOOT28" id="DOCF28"><sup>28</sup></a> <strong>readline</strong> capabilities, the functions described below are available, as well as others (probably) documented in <code class="calibre2">man readline</code> or <code class="calibre2">info readline</code> on your system.</p>
<p>Many of these use either Control or Meta characters. Control characters, such as Control-m, are obtained by holding the <code class="calibre2">CTRL</code> down while you press the <code class="calibre2">m</code> key, and are written as C-m below. Meta characters, such as Meta-b, are typed by holding down <code class="calibre2">META</code><a href="023-R-intro.html#FOOT29" id="DOCF29"><sup>29</sup></a> and pressing <code class="calibre2">b</code>, and written as M-b in the following. If your terminal does not have a <code class="calibre2">META</code> key enabled, you can still type Meta characters using two-character sequences starting with ESC. Thus, to enter M-b, you could type <code class="calibre2">ESC</code><code class="calibre2">b</code>. The ESC character sequences are also allowed on terminals with real Meta keys. Note that case is significant for Meta characters.</p>
<p>Some but not all versions<a href="023-R-intro.html#FOOT30" id="DOCF30"><sup>30</sup></a> of <strong>readline</strong> will recognize resizing of the terminal window so this is best avoided.</p>
<p><a href="" id="Editing-actions"></a></p>
<h3 id="c.2-editing-actions" class="section">C.2 Editing actions</h3>
<p>The R program keeps a history of the command lines you type, including the erroneous lines, and commands in your history may be recalled, changed if necessary, and re-submitted as new commands. In Emacs-style command-line editing any straight typing you do while in this editing phase causes the characters to be inserted in the command you are editing, displacing any characters to the right of the cursor. In <em>vi</em> mode character insertion mode is started by M-i or M-a, characters are typed and insertion mode is finished by typing a further <code class="calibre2">ESC</code>. (The default is Emacs-style, and only that is described here: for <em>vi</em> mode see the <strong>readline</strong> documentation.)</p>
<p>Pressing the <code class="calibre2">RET</code> command at any time causes the command to be re-submitted.</p>
<p>Other editing actions are summarized in the following table.</p>
<p><a href="" id="Command_002dline-editor-summary"></a></p>
<h3 id="c.3-command-line-editor-summary" class="section">C.3 Command-line editor summary</h3>
<p><a href="" id="Command-recall-and-vertical-motion"></a></p>
<h4 id="command-recall-and-vertical-motion" class="subheading">Command recall and vertical motion</h4>
<dl>
<dt>C-p</dt>
<dd><p>Go to the previous command (backwards in the history).</p>
</dd>
<dt>C-n</dt>
<dd><p>Go to the next command (forwards in the history).</p>
</dd>
<dt>C-r text</dt>
<dd><p>Find the last command with the text string in it. This can be cancelled by <code class="calibre2">C-g</code> (and on some versions of R by <code class="calibre2">C-c</code>).</p>
</dd>
</dl>
<p>On most terminals, you can also use the up and down arrow keys instead of C-p and C-n, respectively.</p>
<p><a href="" id="Horizontal-motion-of-the-cursor"></a></p>
<h4 id="horizontal-motion-of-the-cursor" class="subheading">Horizontal motion of the cursor</h4>
<dl>
<dt>C-a</dt>
<dd><p>Go to the beginning of the command.</p>
</dd>
<dt>C-e</dt>
<dd><p>Go to the end of the line.</p>
</dd>
<dt>M-b</dt>
<dd><p>Go back one word.</p>
</dd>
<dt>M-f</dt>
<dd><p>Go forward one word.</p>
</dd>
<dt>C-b</dt>
<dd><p>Go back one character.</p>
</dd>
<dt>C-f</dt>
<dd><p>Go forward one character.</p>
</dd>
</dl>
<p>On most terminals, you can also use the left and right arrow keys instead of C-b and C-f, respectively.</p>
<p><a href="" id="Editing-and-re_002dsubmission"></a></p>
<h4 id="editing-and-re-submission" class="subheading">Editing and re-submission</h4>
<dl>
<dt>text</dt>
<dd><p>Insert text at the cursor.</p>
</dd>
<dt>C-f text</dt>
<dd><p>Append text after the cursor.</p>
</dd>
<dt><span>DEL</span></dt>
<dd><p>Delete the previous character (left of the cursor).</p>
</dd>
<dt>C-d</dt>
<dd><p>Delete the character under the cursor.</p>
</dd>
<dt>M-d</dt>
<dd><p>Delete the rest of the word under the cursor, and “save” it.</p>
</dd>
<dt>C-k</dt>
<dd><p>Delete from cursor to end of command, and “save” it.</p>
</dd>
<dt>C-y</dt>
<dd><p>Insert (yank) the last “saved” text here.</p>
</dd>
<dt>C-t</dt>
<dd><p>Transpose the character under the cursor with the next.</p>
</dd>
<dt>M-l</dt>
<dd><p>Change the rest of the word to lower case.</p>
</dd>
<dt>M-c</dt>
<dd><p>Change the rest of the word to upper case.</p>
</dd>
<dt><span>RET</span></dt>
<dd><p>Re-submit the command to R.</p>
</dd>
</dl>
<p>The final <code class="calibre2">RET</code> terminates the command line editing sequence.</p>
<p>The <strong>readline</strong> key bindings can be customized in the usual way <em>via</em> a ~/.inputrc file. These customizations can be conditioned on application <code class="calibre2">R</code>, that is by including a section like</p>
<div class="example">
<pre class="example1"><code>$if R
  &quot;\C-xd&quot;: &quot;q(&#39;no&#39;)\n&quot;
$endif</code></pre>
</div>
<hr />
<p><a href="" id="Function-and-variable-index"></a> <a href="" id="Function-and-variable-index-1"></a></p>
